### PR TITLE
Generalized Resize

### PR DESCRIPTION
**Pull request by Shoeboxam**
Related to #253

### CODE REVIEW

**Comment by mikephelan** [comment]
by using a naked Some instead of wrapping it in error handlng in validator-rust/src/components/gaussian_mechanism.rs line 169, are you creating the risk of a null error?

**Comment by mikephelan** [comment]
Consider adding a comment in the first reference to analytic, indicating its origin. self.analytic definition?

**Review by mikephelan — APPROVED** [review]
A code safety concern, and lack of findability for a code definition.

**Comment by Shoeboxam** [comment]
> by using a naked Some instead of wrapping it in error handling in validator-rust/src/components/gaussian_mechanism.rs line 169, are you creating the risk of a null error?

Here? https://github.com/opendifferentialprivacy/whitenoise-core/pull/286/files#diff-ac1b8c2212cba362f060ca35454ac03fR169

It is ok to use options generally for things that may or may not exist. Components may or may not have an accuracy implementation. The components that do not have accuracy implementations return `Ok(None)` (successfully returned no known accuracy). In the outside code, errors are cleanly handled with the error handling system, and `Ok(None)` responses are filtered away.

**Comment by Shoeboxam** [comment]
> Consider adding a comment in the first reference to analytic, indicating its origin. self.analytic definition?

Was this comment supposed to be tied to code somewhere?

**Pull request closed without merging**
